type = "about"
title = "About"

[profile]
research_interests = [
  "Computational Physics",
  "Mathematical Principles",
  "Proof of Theorems"
]

[[sections]]
id = "about"
type = "markdown"
source = "bio.md"
title = "About Me"

[[sections]]
id = "news"
type = "list"
title = "News"
source = "news"

[[sections]]
id = "featured_publications"
type = "publications"
title = "Selected Publications"
filter = "selected"
limit = 180

[[sections]]
id = "honors_and_awards"
type = "markdown"
title = "Honors and Awards"
source = "honorsawards.md"

[[sections]]
id = "educations"
type = "markdown"
title = " Educations"
source = "educations.md"

[[sections]]
id = "services"
type = "markdown"
title = "Academic Services"
source = "services.md"

