
[[news]]
date = "2026-7"
content = "One paper was accepted by Pattern Recognition [PR-26], 2026."

[[news]]
date = "2026-7"
content = "One paper was accepted by the 34th ACM International Conference on Multimedia [[ACM MM-26]], 2026."

[[news]]
date = "2026-6"
content = "One paper was accepted by Information Fusion [INF-26], 2026."

[[news]]
date = "2026-2"
content = "A Henan Provincial Youth Student Science Foundation Project is obtained [NSFC-26], 2026."

[[news]]
date = "2025-12"
content = "One paper was accepted by Information Processing & Management [IPM-26], 2026."

[[news]]
date = "2025-12"
content = "One paper was accepted by the 40th AAAI Conference on Artificial Intelligence [AAAI-26 (Oral)], 2026."

[[news]]
date = "2025-9"
content = "A Zhengzhou University Young Student Basic Research Projects (PhD students) Seed Projects is obtained, 2025."

[[news]]
date = "2025-9"
content = "One paper was accepted by Information Sciences [INS-25], 2025."

[[news]]
date = "2025-4"
content = "One paper was accepted by the 39th AAAI Conference on Artificial Intelligence [AAAI-25], 2025."

[[news]]
date = "2024-10"
content = "One paper was accepted by the 32nd ACM International Conference on Multimedia [ACM MM-24], 2024."

[[news]]
date = "2024-01"
content = "One paper was accepted by IEEE Transactions on Neural Networks and Learning Systems [TNNLS-24], 2024."

[[news]]
date = "2023-05"
content = "One paper was accepted by Information Processing & Management [IPM-23 (Highly Cited Paper)], 2023."

[[news]]
date = "2022-10"
content = "One paper was accepted by the 30th ACM International Conference on Multimedia [ACM MM-22], 2022."

