[[news]]
date = "2026-07"
content = "One paper is accepted by Pattern Recognition (SCI-Q1, TOP), 2026."
bold = ["One paper"]
green = ["Pattern Recognition (SCI-Q1, TOP)"]

[[news]]
date = "2026-07"
content = "One paper is accepted by the 34th ACM Multimedia (CCF A), 2026."
bold = ["One paper"]
green = ["the 34th ACM Multimedia (CCF A)"]


[[news]]
date = "2026-06"
content = "One paper is accepted by Information Fusion (SCI-Q1, TOP), 2026."
bold = ["One paper"]
green = ["Information Fusion (SCI-Q1, TOP)"]


[[news]]
date = "2026-02"
content = "A Henan Provincial Youth Student Science Foundation Project (河南省自然青年学生科学基金项目) is obtained, 2026."
bold = ["Henan Provincial Youth Student Science Foundation Project"]
green =["河南省自然青年学生科学基金项目"]

[[news]]
date = "2025-12"
content = "One paper is accepted by Information Processing & Management (SCI-Q1, TOP), 2026."
bold = ["One paper"]
green = ["Information Processing & Management (SCI-Q1, TOP)"]


[[news]]
date = "2025-12"
content = "One paper is accepted by the 40th AAAI [Oral] (CCF A), 2026."
bold = ["One paper", "[Oral]"]
green = ["the 40th AAAI [Oral] (CCF A)"]


[[news]]
date = "2025-09"
content = "A Zhengzhou University Young Student Basic Research Projects Seed Projects (郑州大学青年学生基础研究项目种子项目) is obtained, 2025."
bold = ["Zhengzhou University Young Student Basic Research Projects Seed Projects"]
green =["郑州大学青年学生基础研究项目种子项目"]

[[news]]
date = "2025-09"
content = "One paper is accepted by Information Sciences (SCI-Q2), 2025."
bold = ["One paper"]
green = ["Information Sciences (SCI-Q2)"]


[[news]]
date = "2025-04"
content = "One paper is accepted by the 39th AAAI (CCF A), 2025."
bold = ["One paper"]
green = ["the 39th AAAI (CCF A)"]


[[news]]
date = "2024-10"
content = "One paper is accepted by the 32nd ACM Multimedia (CCF A), 2024."
bold = ["One paper"]
green = ["the 32nd ACM Multimedia (CCF A)"]


[[news]]
date = "2024-01"
content = "One paper is accepted by IEEE Transactions on Neural Networks and Learning Systems (SCI-Q1, TOP), 2024."
bold = ["One paper"]
green = ["IEEE Transactions on Neural Networks and Learning Systems (SCI-Q1, TOP)"]


[[news]]
date = "2023-05"
content = "One paper is accepted by Information Processing & Management [Highly Cited Paper] (SCI-Q1, TOP), 2023."
bold = ["One paper", "[Highly Cited Paper]"]
green = ["Information Processing & Management [Highly Cited Paper] (SCI-Q1, TOP)"]


[[news]]
date = "2022-10"
content = "One paper is accepted by the 30th ACM Multimedia (CCF A), 2022."
bold = ["One paper"]
green = ["the 30th ACM Multimedia (CCF A)"]

